"""Generate MC-dropout tagger configs from the diffusion data-variant configs.

For each ``configs/lsoie_ex_<N>/lsoie_ex_<N>_config.yaml`` this copies the trainer,
data, and schedule fields verbatim and swaps only the ``model`` block for the
non-diffusion tagger (with the *same* extractor so the clustering is identical),
writing ``configs/lsoie_ex_tagger_<N>/lsoie_ex_tagger_<N>_config.yaml``.

Usage::

    uv run python scripts/make_tagger_configs.py            # all variants
    uv run python scripts/make_tagger_configs.py 2500 full  # a subset
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIGS = REPO_ROOT / "configs"

VARIANTS = ["50", "250", "1250", "2500", "full", "plus20k", "plus_full"]


def tagger_model_block(diffusion_model: dict) -> dict:
    """Tagger model block; reuse the source extractor so clustering is identical."""
    extractor = diffusion_model.get(
        "extractor", {"type": "lenient_frequency", "k": 512, "topk": 4, "threshold": 0.9}
    )
    return {
        "type": "mc_dropout_tagger",
        "encoder": {
            "model_name": "bert-base-uncased",
            "freeze": False,
            "num_frozen_layers": 4,
        },
        "dropout": 0.3,
        "temperature": 1.0,
        "argmax": True,
        "inference_chunk_size": 128,
        "extractor": extractor,
    }


def make_one(variant: str) -> Path:
    src = CONFIGS / f"lsoie_ex_{variant}" / f"lsoie_ex_{variant}_config.yaml"
    if not src.exists():
        raise FileNotFoundError(f"Source config not found: {src}")

    with open(src) as f:
        cfg = yaml.safe_load(f)

    cfg["model"] = tagger_model_block(cfg.get("model", {}))
    out_dir = CONFIGS / f"lsoie_ex_tagger_{variant}"
    cfg["save_path"] = f"configs/lsoie_ex_tagger_{variant}"

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"lsoie_ex_tagger_{variant}_config.yaml"
    header = (
        f"# MC-dropout BERT tagger baseline (non-diffusion) for the '{variant}' data\n"
        f"# variant. Generated by scripts/make_tagger_configs.py from\n"
        f"# {src.relative_to(REPO_ROOT)} — trainer/data reused verbatim, only the\n"
        f"# model block swapped. Isolates diffusion vs. stochastic-tagging+clustering.\n"
    )
    with open(out_path, "w") as f:
        f.write(header)
        yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
    return out_path


def main() -> None:
    wanted = sys.argv[1:] or VARIANTS
    unknown = [v for v in wanted if v not in VARIANTS]
    if unknown:
        raise SystemExit(f"Unknown variant(s): {unknown}. Choose from {VARIANTS}")
    for v in wanted:
        print(f"wrote {make_one(v).relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
